const WIZARD_STEPS = ['title', 'description', 'price', 'category', 'size', 'condition', 'colour', 'brand', 'parcel', 'confirm'];

const ADMIN_VINTED_USERNAMES = ['zaruha'];

const CONDITIONS = [
  { id: 6, label: 'New with tags', emoji: '🏷️' },
  { id: 1, label: 'New without tags', emoji: '✨' },
  { id: 2, label: 'Very good', emoji: '👍' },
  { id: 3, label: 'Good', emoji: '👌' },
  { id: 4, label: 'Satisfactory', emoji: '🔧' },
];

const PACKAGE_SIZES = [
  { id: 1, title: 'Small', desc: 'Up to 2kg, fits in a large letter' },
  { id: 2, title: 'Medium', desc: 'Up to 5kg, shoebox size' },
  { id: 3, title: 'Large', desc: 'Up to 10kg, large box' },
];

const CATEGORIES = [
  // WOMEN > CLOTHING
  { id: 1043, title: 'Women > Tops > Blouses', keywords: ['blouse','women blouse'] },
  { id: 221, title: 'Women > Tops > T-shirts', keywords: ['t-shirt','tshirt','tee','women t-shirt','women tee'] },
  { id: 1041, title: 'Women > Tops > Crop tops', keywords: ['crop top','cropped'] },
  { id: 224, title: 'Women > Tops > Long-sleeved tops', keywords: ['long sleeve','women long sleeve'] },
  { id: 534, title: 'Women > Tops > Vest tops', keywords: ['vest','tank top','cami','vest top'] },
  { id: 222, title: 'Women > Tops > Shirts', keywords: ['shirt','women shirt'] },
  { id: 223, title: 'Women > Tops > Short-sleeved tops', keywords: ['short sleeve','women short sleeve'] },
  { id: 14, title: 'Women > Tops > Camis', keywords: ['camisole','women cami'] },
  { id: 1042, title: 'Women > Tops > Off-the-shoulder tops', keywords: ['off shoulder','bardot'] },
  { id: 1835, title: 'Women > Tops > Bodysuits', keywords: ['bodysuit','body'] },
  { id: 225, title: 'Women > Tops > 3/4-sleeve tops', keywords: ['3/4 sleeve'] },
  { id: 1044, title: 'Women > Tops > Halterneck tops', keywords: ['halterneck','halter'] },
  { id: 227, title: 'Women > Tops > Tunics', keywords: ['tunic'] },
  { id: 1837, title: 'Women > Tops > Peplum tops', keywords: ['peplum'] },
  { id: 1045, title: 'Women > Tops > Turtlenecks', keywords: ['turtleneck','roll neck','polo neck'] },
  { id: 228, title: 'Women > Tops > Other tops', keywords: ['women top','top'] },
  // Women > Dresses
  { id: 1065, title: 'Women > Dresses > Summer dresses', keywords: ['summer dress','sundress'] },
  { id: 1055, title: 'Women > Dresses > Long dresses', keywords: ['long dress','maxi dress','maxi'] },
  { id: 1774, title: 'Women > Dresses > Special-occasion dresses', keywords: ['special occasion dress','prom dress','evening dress'] },
  { id: 1056, title: 'Women > Dresses > Midi dresses', keywords: ['midi dress','midi'] },
  { id: 178, title: 'Women > Dresses > Mini dresses', keywords: ['mini dress'] },
  { id: 1059, title: 'Women > Dresses > Casual dresses', keywords: ['casual dress'] },
  { id: 1058, title: 'Women > Dresses > Little black dresses', keywords: ['little black dress','lbd'] },
  { id: 1057, title: 'Women > Dresses > Formal & work dresses', keywords: ['formal dress','work dress'] },
  { id: 1061, title: 'Women > Dresses > Strapless dresses', keywords: ['strapless dress','bandeau dress'] },
  { id: 179, title: 'Women > Dresses > Denim dresses', keywords: ['denim dress','jeans dress'] },
  { id: 1779, title: 'Women > Dresses > Winter dresses', keywords: ['winter dress','knitted dress'] },
  { id: 176, title: 'Women > Dresses > Other dresses', keywords: ['dress','gown','women dress'] },
  // Women > Jumpers & Sweaters
  { id: 1917, title: 'Women > Jumpers > Jumpers', keywords: ['jumper','women jumper','pullover'] },
  { id: 196, title: 'Women > Jumpers > Hoodies & sweatshirts', keywords: ['hoodie','sweatshirt','women hoodie'] },
  { id: 194, title: 'Women > Jumpers > Cardigans', keywords: ['cardigan','women cardigan'] },
  { id: 1874, title: 'Women > Jumpers > Waistcoats', keywords: ['waistcoat','women waistcoat','gilet'] },
  { id: 1067, title: 'Women > Jumpers > Kimonos', keywords: ['kimono'] },
  { id: 195, title: 'Women > Jumpers > Boleros', keywords: ['bolero','shrug'] },
  { id: 197, title: 'Women > Jumpers > Other jumpers', keywords: ['sweater','knitwear','knit'] },
  // Women > Outerwear
  { id: 1908, title: 'Women > Outerwear > Jackets', keywords: ['jacket','bomber','denim jacket','women jacket'] },
  { id: 1907, title: 'Women > Outerwear > Coats', keywords: ['coat','parka','puffer','trench','raincoat','women coat'] },
  { id: 2524, title: 'Women > Outerwear > Gilets & body warmers', keywords: ['gilet','body warmer','women gilet'] },
  { id: 1773, title: 'Women > Outerwear > Capes & ponchos', keywords: ['cape','poncho'] },
  // Women > Trousers & Leggings
  { id: 1071, title: 'Women > Trousers > Wide-leg trousers', keywords: ['wide leg','palazzo'] },
  { id: 525, title: 'Women > Trousers > Leggings', keywords: ['leggings','women leggings'] },
  { id: 1846, title: 'Women > Trousers > Straight-leg trousers', keywords: ['straight leg trousers'] },
  { id: 187, title: 'Women > Trousers > Tailored trousers', keywords: ['tailored','women tailored'] },
  { id: 184, title: 'Women > Trousers > Leather trousers', keywords: ['leather trousers'] },
  { id: 1070, title: 'Women > Trousers > Cropped trousers & chinos', keywords: ['chinos','cropped trousers'] },
  { id: 185, title: 'Women > Trousers > Skinny trousers', keywords: ['skinny trousers'] },
  { id: 526, title: 'Women > Trousers > Harem pants', keywords: ['harem pants','harem'] },
  { id: 189, title: 'Women > Trousers > Other trousers', keywords: ['trousers','pants','joggers','cargo','women trousers'] },
  // Women > Jeans
  { id: 1844, title: 'Women > Jeans > Skinny jeans', keywords: ['skinny jeans','women skinny'] },
  { id: 1845, title: 'Women > Jeans > Straight jeans', keywords: ['straight jeans','women straight'] },
  { id: 1842, title: 'Women > Jeans > High waisted jeans', keywords: ['high waisted','high waist jeans','mom jeans'] },
  { id: 1843, title: 'Women > Jeans > Ripped jeans', keywords: ['ripped jeans','distressed jeans'] },
  { id: 1841, title: 'Women > Jeans > Flared jeans', keywords: ['flared jeans','wide leg jeans','bootcut'] },
  { id: 1839, title: 'Women > Jeans > Boyfriend jeans', keywords: ['boyfriend jeans'] },
  { id: 1840, title: 'Women > Jeans > Cropped jeans', keywords: ['cropped jeans'] },
  { id: 1864, title: 'Women > Jeans > Other jeans', keywords: ['jeans','denim','women jeans'] },
  // Women > Skirts
  { id: 198, title: 'Women > Skirts > Mini skirts', keywords: ['mini skirt'] },
  { id: 199, title: 'Women > Skirts > Midi skirts', keywords: ['midi skirt'] },
  { id: 200, title: 'Women > Skirts > Maxi skirts', keywords: ['maxi skirt'] },
  { id: 2927, title: 'Women > Skirts > Knee-length skirts', keywords: ['knee length skirt','pencil skirt'] },
  { id: 2928, title: 'Women > Skirts > Asymmetric skirts', keywords: ['asymmetric skirt'] },
  // Women > Shorts
  { id: 538, title: 'Women > Shorts > Denim shorts', keywords: ['denim shorts','jean shorts'] },
  { id: 1099, title: 'Women > Shorts > High-waisted shorts', keywords: ['high waisted shorts'] },
  { id: 203, title: 'Women > Shorts > Knee-length shorts', keywords: ['knee length shorts','bermuda'] },
  { id: 1103, title: 'Women > Shorts > Cargo shorts', keywords: ['cargo shorts'] },
  { id: 1101, title: 'Women > Shorts > Lace shorts', keywords: ['lace shorts'] },
  { id: 1100, title: 'Women > Shorts > Leather shorts', keywords: ['leather shorts'] },
  { id: 204, title: 'Women > Shorts > Cropped trousers', keywords: ['cropped trousers','capri'] },
  { id: 1838, title: 'Women > Shorts > Low-waisted shorts', keywords: ['low waisted shorts'] },
  { id: 205, title: 'Women > Shorts > Other shorts', keywords: ['shorts','hot pants','women shorts'] },
  // Women > Activewear
  { id: 576, title: 'Women > Activewear > Tops & t-shirts', keywords: ['sports top','gym top','women sports top'] },
  { id: 572, title: 'Women > Activewear > Tracksuits', keywords: ['tracksuit','women tracksuit'] },
  { id: 578, title: 'Women > Activewear > Shorts', keywords: ['gym shorts','sports shorts','women sports shorts'] },
  { id: 573, title: 'Women > Activewear > Trousers', keywords: ['gym leggings','sports leggings','yoga pants'] },
  { id: 574, title: 'Women > Activewear > Dresses', keywords: ['sports dress','tennis dress'] },
  { id: 1439, title: 'Women > Activewear > Sports bras', keywords: ['sports bra'] },
  { id: 571, title: 'Women > Activewear > Outerwear', keywords: ['sports jacket','running jacket'] },
  { id: 577, title: 'Women > Activewear > Hoodies & sweatshirts', keywords: ['sports hoodie','gym hoodie'] },
  { id: 575, title: 'Women > Activewear > Skirts', keywords: ['sports skirt','tennis skirt'] },
  { id: 3268, title: 'Women > Activewear > Team shirts & jerseys', keywords: ['women team shirt','women jersey'] },
  { id: 579, title: 'Women > Activewear > Sports accessories', keywords: ['sports accessories','gym accessories'] },
  { id: 580, title: 'Women > Activewear > Other activewear', keywords: ['activewear','sportswear','gym','running','yoga'] },
  // Women > Swimwear
  { id: 219, title: 'Women > Swimwear > Bikinis & tankinis', keywords: ['bikini','tankini'] },
  { id: 218, title: 'Women > Swimwear > One-pieces', keywords: ['swimsuit','one-piece','bathing suit'] },
  { id: 1780, title: 'Women > Swimwear > Cover-ups & sarongs', keywords: ['cover up','sarong','beach cover'] },
  { id: 220, title: 'Women > Swimwear > Other swimwear', keywords: ['swimwear','swimming','beachwear'] },
  // Women > Lingerie & Nightwear
  { id: 119, title: 'Women > Lingerie > Bras', keywords: ['bra','bralette'] },
  { id: 120, title: 'Women > Lingerie > Panties', keywords: ['panties','knickers','thong','underwear'] },
  { id: 229, title: 'Women > Lingerie > Sets', keywords: ['lingerie set','underwear set'] },
  { id: 123, title: 'Women > Lingerie > Nightwear', keywords: ['pyjamas','nightwear','sleepwear','nightdress'] },
  { id: 1030, title: 'Women > Lingerie > Dressing gowns', keywords: ['dressing gown','robe','bathrobe'] },
  { id: 1262, title: 'Women > Lingerie > Socks', keywords: ['women socks'] },
  { id: 1263, title: 'Women > Lingerie > Tights & stockings', keywords: ['tights','stockings','hosiery'] },
  { id: 1781, title: 'Women > Lingerie > Shapewear', keywords: ['shapewear','corset'] },
  { id: 1847, title: 'Women > Lingerie > Lingerie accessories', keywords: ['lingerie accessories'] },
  { id: 124, title: 'Women > Lingerie > Other lingerie', keywords: ['lingerie'] },
  // Women > Jumpsuits & Playsuits
  { id: 1131, title: 'Women > Jumpsuits & Playsuits > Jumpsuits', keywords: ['jumpsuit','dungarees'] },
  { id: 1132, title: 'Women > Jumpsuits & Playsuits > Playsuits', keywords: ['playsuit','romper'] },
  { id: 1134, title: 'Women > Jumpsuits & Playsuits > Other', keywords: ['women jumpsuit','women playsuit'] },
  // Women > Suits & Blazers
  { id: 532, title: 'Women > Suits > Blazers', keywords: ['blazer','women blazer'] },
  { id: 1126, title: 'Women > Suits > Skirt suits', keywords: ['skirt suit'] },
  { id: 1125, title: 'Women > Suits > Trouser suits', keywords: ['trouser suit','women suit'] },
  { id: 1128, title: 'Women > Suits > Suit separates', keywords: ['suit separates'] },
  { id: 1129, title: 'Women > Suits > Other suits', keywords: ['women formal'] },
  // Women > Other clothing
  { id: 18, title: 'Women > Other clothing', keywords: ['women clothing'] },
  { id: 1176, title: 'Women > Maternity clothes', keywords: ['maternity','pregnancy','pregnant'] },
  { id: 1782, title: 'Women > Costumes & special outfits', keywords: ['costume','fancy dress','halloween','women costume'] },
  { id: 5491, title: 'Women > Skorts', keywords: ['skort'] },
  // WOMEN > SHOES
  { id: 2632, title: 'Women > Shoes > Trainers', keywords: ['women trainers','women sneakers'] },
  { id: 543, title: 'Women > Shoes > Heels', keywords: ['heels','high heels','stilettos'] },
  { id: 1049, title: 'Women > Shoes > Boots', keywords: ['women boots','ankle boots','knee boots','chelsea boots'] },
  { id: 2949, title: 'Women > Shoes > Sandals', keywords: ['women sandals'] },
  { id: 2630, title: 'Women > Shoes > Sports shoes', keywords: ['women sports shoes','running shoes'] },
  { id: 2952, title: 'Women > Shoes > Flip-flops & slides', keywords: ['flip flops','slides','women slides'] },
  { id: 2954, title: 'Women > Shoes > Boat shoes, loafers & moccasins', keywords: ['loafers','moccasins','boat shoes'] },
  { id: 2623, title: 'Women > Shoes > Clogs & mules', keywords: ['clogs','mules'] },
  { id: 2955, title: 'Women > Shoes > Ballerinas', keywords: ['ballerinas','ballet flats','flats'] },
  { id: 215, title: 'Women > Shoes > Slippers', keywords: ['women slippers'] },
  { id: 2951, title: 'Women > Shoes > Lace-up shoes', keywords: ['lace up shoes','brogues','women brogues'] },
  { id: 2953, title: 'Women > Shoes > Espadrilles', keywords: ['espadrilles'] },
  { id: 2950, title: 'Women > Shoes > Mary Janes & T-bar shoes', keywords: ['mary jane','t-bar'] },
  // WOMEN > BAGS
  { id: 156, title: 'Women > Bags > Handbags', keywords: ['handbag'] },
  { id: 158, title: 'Women > Bags > Shoulder bags', keywords: ['shoulder bag','crossbody'] },
  { id: 552, title: 'Women > Bags > Tote bags', keywords: ['tote','tote bag'] },
  { id: 157, title: 'Women > Bags > Backpacks', keywords: ['backpack','rucksack','women backpack'] },
  { id: 159, title: 'Women > Bags > Clutches', keywords: ['clutch','evening bag'] },
  { id: 160, title: 'Women > Bags > Wallets & purses', keywords: ['purse','women wallet','coin purse'] },
  { id: 161, title: 'Women > Bags > Makeup bags', keywords: ['makeup bag','cosmetic bag','toiletry bag'] },
  { id: 1784, title: 'Women > Bags > Satchels & messenger bags', keywords: ['satchel','messenger bag'] },
  { id: 2940, title: 'Women > Bags > Beach bags', keywords: ['beach bag'] },
  { id: 2942, title: 'Women > Bags > Bucket bags', keywords: ['bucket bag'] },
  { id: 1848, title: 'Women > Bags > Bum bags', keywords: ['bum bag','fanny pack','belt bag'] },
  { id: 1849, title: 'Women > Bags > Holdalls & duffel bags', keywords: ['holdall','duffel','weekender'] },
  { id: 2945, title: 'Women > Bags > Hobo bags', keywords: ['hobo bag'] },
  { id: 2939, title: 'Women > Bags > Wristlets', keywords: ['wristlet'] },
  { id: 2943, title: 'Women > Bags > Garment bags', keywords: ['garment bag'] },
  { id: 1850, title: 'Women > Bags > Luggage & suitcases', keywords: ['luggage','suitcase','travel bag'] },
  { id: 2941, title: 'Women > Bags > Briefcases', keywords: ['briefcase','women briefcase'] },
  { id: 2944, title: 'Women > Bags > Gym bags', keywords: ['gym bag','sports bag'] },
  // WOMEN > ACCESSORIES
  { id: 164, title: 'Women > Jewellery > Necklaces', keywords: ['necklace','pendant','chain'] },
  { id: 163, title: 'Women > Jewellery > Earrings', keywords: ['earrings','studs','hoops'] },
  { id: 165, title: 'Women > Jewellery > Bracelets', keywords: ['bracelet','bangle'] },
  { id: 553, title: 'Women > Jewellery > Rings', keywords: ['ring','women ring'] },
  { id: 166, title: 'Women > Jewellery > Jewellery sets', keywords: ['jewellery set','jewelry set'] },
  { id: 167, title: 'Women > Jewellery > Brooches', keywords: ['brooch','pin'] },
  { id: 2938, title: 'Women > Jewellery > Charms & pendants', keywords: ['charm','pendant'] },
  { id: 2937, title: 'Women > Jewellery > Body jewellery', keywords: ['body jewellery','body chain'] },
  { id: 1785, title: 'Women > Jewellery > Anklets', keywords: ['anklet'] },
  { id: 162, title: 'Women > Jewellery > Other jewellery', keywords: ['jewellery','jewelry','women jewellery'] },
  { id: 88, title: 'Women > Accessories > Hats & caps', keywords: ['hat','beanie','beret','women cap','women hat'] },
  { id: 89, title: 'Women > Accessories > Scarves & shawls', keywords: ['scarf','shawl','women scarf'] },
  { id: 1852, title: 'Women > Accessories > Keyrings', keywords: ['keyring','key chain'] },
  { id: 1123, title: 'Women > Accessories > Hair accessories', keywords: ['hair clip','headband','scrunchie','hair tie','hair accessory'] },
  { id: 26, title: 'Women > Accessories > Sunglasses', keywords: ['women sunglasses','women glasses'] },
  { id: 22, title: 'Women > Accessories > Watches', keywords: ['women watch','ladies watch'] },
  { id: 20, title: 'Women > Accessories > Belts', keywords: ['women belt','ladies belt'] },
  { id: 90, title: 'Women > Accessories > Gloves', keywords: ['women gloves','mittens'] },
  { id: 2931, title: 'Women > Accessories > Bandanas & headscarves', keywords: ['bandana','headscarf'] },
  { id: 1851, title: 'Women > Accessories > Umbrellas', keywords: ['umbrella'] },
  { id: 2932, title: 'Women > Accessories > Handkerchiefs', keywords: ['handkerchief'] },
  { id: 1140, title: 'Women > Accessories > Other accessories', keywords: ['accessory','women accessory'] },
  // WOMEN > BEAUTY
  { id: 964, title: 'Women > Beauty > Make-up', keywords: ['makeup','make-up','lipstick','foundation','mascara','eyeshadow'] },
  { id: 948, title: 'Women > Beauty > Facial care', keywords: ['facial care','face cream','moisturiser','serum','cleanser'] },
  { id: 1906, title: 'Women > Beauty > Beauty tools', keywords: ['beauty tools','makeup brush','mirror','tweezers'] },
  { id: 956, title: 'Women > Beauty > Body care', keywords: ['body cream','body lotion','shower gel','bath bomb'] },
  { id: 152, title: 'Women > Beauty > Perfume', keywords: ['perfume','fragrance','eau de toilette','women perfume'] },
  { id: 1902, title: 'Women > Beauty > Hair care', keywords: ['hair care','shampoo','conditioner','hair mask','hair straightener'] },
  { id: 960, title: 'Women > Beauty > Nail care', keywords: ['nail polish','nail care','manicure'] },
  { id: 1264, title: 'Women > Beauty > Hand care', keywords: ['hand cream','hand care'] },
  { id: 153, title: 'Women > Beauty > Other beauty', keywords: ['beauty','skincare'] },
  // MEN > CLOTHING
  { id: 77, title: 'Men > Tops > T-shirts', keywords: ['men t-shirt','mens tee','men tshirt'] },
  { id: 536, title: 'Men > Tops > Shirts', keywords: ['men shirt','mens shirt','dress shirt'] },
  { id: 5492, title: 'Men > Tops > Polo shirts', keywords: ['polo','polo shirt','men polo'] },
  { id: 560, title: 'Men > Tops > Vests & sleeveless', keywords: ['men vest','sleeveless','men tank top'] },
  // Men > Jumpers & Sweaters
  { id: 267, title: 'Men > Jumpers > Hoodies & sweaters', keywords: ['men hoodie','mens hoodie','men sweatshirt'] },
  { id: 1811, title: 'Men > Jumpers > Jumpers', keywords: ['men jumper','mens jumper','men pullover'] },
  { id: 1812, title: 'Men > Jumpers > Zip-through hoodies', keywords: ['zip hoodie','zip through hoodie'] },
  { id: 1813, title: 'Men > Jumpers > Crew neck jumpers', keywords: ['crew neck','crewneck'] },
  { id: 264, title: 'Men > Jumpers > V-neck jumpers', keywords: ['v-neck jumper','v neck'] },
  { id: 1815, title: 'Men > Jumpers > Chunky-knit jumpers', keywords: ['chunky knit','cable knit'] },
  { id: 1814, title: 'Men > Jumpers > Long jumpers', keywords: ['long jumper'] },
  { id: 266, title: 'Men > Jumpers > Cardigans', keywords: ['men cardigan','mens cardigan'] },
  { id: 265, title: 'Men > Jumpers > Turtleneck jumpers', keywords: ['men turtleneck','men roll neck'] },
  { id: 1825, title: 'Men > Jumpers > Sleeveless jumpers', keywords: ['sleeveless jumper','tank top jumper'] },
  { id: 268, title: 'Men > Jumpers > Other jumpers', keywords: ['mens sweater','knitwear'] },
  // Men > Outerwear
  { id: 2052, title: 'Men > Outerwear > Jackets', keywords: ['men jacket','mens jacket','bomber','men bomber'] },
  { id: 2051, title: 'Men > Outerwear > Coats', keywords: ['men coat','mens coat','men parka','men puffer'] },
  { id: 2553, title: 'Men > Outerwear > Gilets & body warmers', keywords: ['men gilet','men body warmer'] },
  { id: 2552, title: 'Men > Outerwear > Ponchos', keywords: ['men poncho'] },
  // Men > Trousers
  { id: 1821, title: 'Men > Trousers > Joggers', keywords: ['men joggers','mens joggers','tracksuit bottoms'] },
  { id: 1820, title: 'Men > Trousers > Chinos', keywords: ['men chinos','chinos'] },
  { id: 261, title: 'Men > Trousers > Tailored trousers', keywords: ['men tailored','men formal trousers'] },
  { id: 260, title: 'Men > Trousers > Wide-legged trousers', keywords: ['men wide leg'] },
  { id: 259, title: 'Men > Trousers > Skinny trousers', keywords: ['men skinny trousers'] },
  { id: 271, title: 'Men > Trousers > Cropped trousers', keywords: ['men cropped trousers'] },
  { id: 263, title: 'Men > Trousers > Other trousers', keywords: ['men trousers','mens pants','mens cargo'] },
  // Men > Jeans
  { id: 1819, title: 'Men > Jeans > Straight fit', keywords: ['men straight jeans'] },
  { id: 1818, title: 'Men > Jeans > Slim fit', keywords: ['men slim jeans','slim fit jeans'] },
  { id: 1817, title: 'Men > Jeans > Skinny', keywords: ['men skinny jeans'] },
  { id: 1816, title: 'Men > Jeans > Ripped', keywords: ['men ripped jeans','men distressed jeans'] },
  // Men > Shorts
  { id: 1823, title: 'Men > Shorts > Chino shorts', keywords: ['men chino shorts'] },
  { id: 1824, title: 'Men > Shorts > Denim shorts', keywords: ['men denim shorts'] },
  { id: 1822, title: 'Men > Shorts > Cargo shorts', keywords: ['men cargo shorts'] },
  { id: 272, title: 'Men > Shorts > Other shorts', keywords: ['men shorts','mens shorts'] },
  // Men > Activewear
  { id: 584, title: 'Men > Activewear > Tops & t-shirts', keywords: ['men sports top','men gym top'] },
  { id: 3267, title: 'Men > Activewear > Team shirts & jerseys', keywords: ['football shirt','jersey','team shirt','football top'] },
  { id: 582, title: 'Men > Activewear > Tracksuits', keywords: ['men tracksuit','mens tracksuit'] },
  { id: 581, title: 'Men > Activewear > Outerwear', keywords: ['men sports jacket'] },
  { id: 586, title: 'Men > Activewear > Shorts', keywords: ['men sports shorts','men gym shorts'] },
  { id: 583, title: 'Men > Activewear > Trousers', keywords: ['men sports trousers','men gym trousers'] },
  { id: 585, title: 'Men > Activewear > Pullovers & sweaters', keywords: ['men sports pullover'] },
  { id: 587, title: 'Men > Activewear > Sports accessories', keywords: ['men sports accessories'] },
  { id: 588, title: 'Men > Activewear > Other activewear', keywords: ['men sportswear','men gym','men activewear'] },
  // Men > Other clothing
  { id: 84, title: 'Men > Swimwear', keywords: ['men swimwear','swim trunks','swim shorts'] },
  { id: 85, title: 'Men > Socks & underwear', keywords: ['men socks','men underwear','boxers','briefs'] },
  { id: 2910, title: 'Men > Sleepwear', keywords: ['men pyjamas','men sleepwear','men dressing gown'] },
  { id: 92, title: 'Men > Costumes & special outfits', keywords: ['men costume','men fancy dress'] },
  { id: 83, title: 'Men > Other clothing', keywords: ['men clothing'] },
  // Men > Suits & Blazers
  { id: 1786, title: 'Men > Suits > Suit jackets & blazers', keywords: ['men blazer','suit jacket','mens blazer'] },
  { id: 1789, title: 'Men > Suits > Suit sets', keywords: ['men suit','suit set'] },
  { id: 1787, title: 'Men > Suits > Suit trousers', keywords: ['suit trousers','men formal trousers'] },
  { id: 1788, title: 'Men > Suits > Waistcoats', keywords: ['men waistcoat'] },
  { id: 1790, title: 'Men > Suits > Wedding suits', keywords: ['wedding suit','morning suit'] },
  { id: 1866, title: 'Men > Suits > Other suits', keywords: ['men formal'] },
  // MEN > SHOES
  { id: 1242, title: 'Men > Shoes > Trainers', keywords: ['men trainers','mens sneakers','men sneakers'] },
  { id: 1452, title: 'Men > Shoes > Sports shoes', keywords: ['men sports shoes','men running shoes'] },
  { id: 1233, title: 'Men > Shoes > Boots', keywords: ['men boots','mens boots'] },
  { id: 1238, title: 'Men > Shoes > Formal shoes', keywords: ['men formal shoes','dress shoes','oxford','brogues'] },
  { id: 2656, title: 'Men > Shoes > Boat shoes, loafers & moccasins', keywords: ['men loafers','men moccasins','boat shoes'] },
  { id: 2969, title: 'Men > Shoes > Flip-flops & slides', keywords: ['men flip flops','men slides'] },
  { id: 2659, title: 'Men > Shoes > Slippers', keywords: ['men slippers'] },
  { id: 2968, title: 'Men > Shoes > Sandals', keywords: ['men sandals','mens sandals'] },
  { id: 2970, title: 'Men > Shoes > Clogs & mules', keywords: ['men clogs','men mules'] },
  { id: 2657, title: 'Men > Shoes > Espadrilles', keywords: ['men espadrilles'] },
  // MEN > ACCESSORIES
  { id: 86, title: 'Men > Accessories > Hats & caps', keywords: ['men hat','mens hat','men cap','snapback'] },
  { id: 94, title: 'Men > Accessories > Bags & backpacks', keywords: ['men bag','mens bag','men rucksack','men backpack'] },
  { id: 95, title: 'Men > Accessories > Jewellery', keywords: ['men jewellery','men chain','men ring','men bracelet'] },
  { id: 2956, title: 'Men > Accessories > Ties & bow ties', keywords: ['tie','bow tie','cufflinks'] },
  { id: 97, title: 'Men > Accessories > Watches', keywords: ['men watch','mens watch'] },
  { id: 87, title: 'Men > Accessories > Scarves & shawls', keywords: ['men scarf','mens scarf'] },
  { id: 98, title: 'Men > Accessories > Sunglasses', keywords: ['men sunglasses','mens sunglasses'] },
  { id: 96, title: 'Men > Accessories > Belts', keywords: ['men belt','mens belt'] },
  { id: 91, title: 'Men > Accessories > Gloves', keywords: ['men gloves','mens gloves'] },
  { id: 2960, title: 'Men > Accessories > Bandanas & headscarves', keywords: ['men bandana'] },
  { id: 2959, title: 'Men > Accessories > Braces', keywords: ['braces','suspenders'] },
  { id: 2957, title: 'Men > Accessories > Pocket squares', keywords: ['pocket square'] },
  { id: 99, title: 'Men > Accessories > Other accessories', keywords: ['men accessory','men accessories','wallet','card holder'] },
  // MEN > GROOMING
  { id: 145, title: 'Men > Grooming > Aftershave & cologne', keywords: ['aftershave','cologne','men fragrance','men perfume'] },
  { id: 141, title: 'Men > Grooming > Body care', keywords: ['men body care','men shower gel'] },
  { id: 143, title: 'Men > Grooming > Facial care', keywords: ['men facial care','men moisturiser'] },
  { id: 2055, title: 'Men > Grooming > Tools & accessories', keywords: ['men grooming tools','razor','trimmer'] },
  { id: 1863, title: 'Men > Grooming > Grooming kits', keywords: ['grooming kit','men gift set'] },
  { id: 140, title: 'Men > Grooming > Hair care', keywords: ['men hair care','pomade','wax','hair gel'] },
  { id: 142, title: 'Men > Grooming > Hand & nail care', keywords: ['men hand care'] },
  { id: 144, title: 'Men > Grooming > Make-up', keywords: ['men makeup'] },
  { id: 968, title: 'Men > Grooming > Other grooming', keywords: ['grooming','men grooming'] },
  // KIDS
  { id: 1247, title: 'Kids > Girls > Dresses', keywords: ['girls dress','girl dress'] },
  { id: 1245, title: 'Kids > Girls > Tops & T-shirts', keywords: ['girls top','girls t-shirt'] },
  { id: 1249, title: 'Kids > Girls > Trousers, shorts & dungarees', keywords: ['girls trousers','girls shorts','girls dungarees'] },
  { id: 1246, title: 'Kids > Girls > Jumpers & hoodies', keywords: ['girls jumper','girls hoodie'] },
  { id: 1244, title: 'Kids > Girls > Outerwear', keywords: ['girls coat','girls jacket'] },
  { id: 1248, title: 'Kids > Girls > Skirts', keywords: ['girls skirt'] },
  { id: 1594, title: 'Kids > Girls > Sleepwear & nightwear', keywords: ['girls pyjamas','girls nightwear'] },
  { id: 1251, title: 'Kids > Girls > Swimwear', keywords: ['girls swimwear','girls bikini','girls swimsuit'] },
  { id: 2080, title: 'Kids > Girls > Formal wear', keywords: ['girls formal','flower girl','girls party dress'] },
  { id: 1253, title: 'Kids > Girls > Activewear', keywords: ['girls activewear','girls sportswear'] },
  { id: 1252, title: 'Kids > Girls > Underwear & socks', keywords: ['girls underwear','girls socks'] },
  { id: 1606, title: 'Kids > Girls > Fancy dress & costumes', keywords: ['girls costume','girls fancy dress'] },
  { id: 1510, title: 'Kids > Girls > Clothing bundles', keywords: ['girls bundle','girls clothing bundle'] },
  { id: 1254, title: 'Kids > Girls > Other', keywords: ['girls clothing'] },
  { id: 1255, title: 'Kids > Girls > Shoes', keywords: ['girls shoes'] },
  { id: 1258, title: 'Kids > Girls > Bags & backpacks', keywords: ['girls bag','girls backpack'] },
  { id: 1574, title: 'Kids > Girls > Accessories', keywords: ['girls accessories','girls jewellery','girls hat'] },
  { id: 1198, title: 'Kids > Boys > Tops & T-shirts', keywords: ['boys top','boys t-shirt'] },
  { id: 1200, title: 'Kids > Boys > Trousers, shorts & dungarees', keywords: ['boys trousers','boys shorts','boys dungarees'] },
  { id: 1199, title: 'Kids > Boys > Jumpers & hoodies', keywords: ['boys jumper','boys hoodie'] },
  { id: 1197, title: 'Kids > Boys > Outerwear', keywords: ['boys coat','boys jacket'] },
  { id: 1204, title: 'Kids > Boys > Activewear', keywords: ['boys activewear','boys sportswear','boys football'] },
  { id: 1752, title: 'Kids > Boys > Sleepwear', keywords: ['boys pyjamas','boys sleepwear'] },
  { id: 1202, title: 'Kids > Boys > Swimwear', keywords: ['boys swimwear','boys swim trunks'] },
  { id: 2083, title: 'Kids > Boys > Formal wear', keywords: ['boys formal','boys suit','page boy'] },
  { id: 1203, title: 'Kids > Boys > Underwear & socks', keywords: ['boys underwear','boys socks'] },
  { id: 1762, title: 'Kids > Boys > Fancy dress & costumes', keywords: ['boys costume','boys fancy dress'] },
  { id: 1760, title: 'Kids > Boys > Clothing bundles', keywords: ['boys bundle','boys clothing bundle'] },
  { id: 1205, title: 'Kids > Boys > Other', keywords: ['boys clothing'] },
  { id: 1256, title: 'Kids > Boys > Shoes', keywords: ['boys shoes'] },
  { id: 1257, title: 'Kids > Boys > Bags & backpacks', keywords: ['boys bag','boys backpack'] },
  { id: 1714, title: 'Kids > Boys > Accessories', keywords: ['boys accessories','boys hat','boys cap'] },
  { id: 1243, title: 'Kids > Baby girls clothing', keywords: ['baby girl','baby dress','newborn girl'] },
  { id: 1196, title: 'Kids > Baby boys clothing', keywords: ['baby boy','babygrow','onesie','romper','newborn boy'] },
  // Kids > Toys
  { id: 1730, title: 'Kids > Toys > Toy figures & accessories', keywords: ['action figure','figurine','toy figure'] },
  { id: 1764, title: 'Kids > Toys > Soft toys & stuffed animals', keywords: ['teddy','plush','soft toy','stuffed animal','cuddly toy'] },
  { id: 1767, title: 'Kids > Toys > Blocks & building toys', keywords: ['lego','blocks','building','duplo','megabloks'] },
  { id: 3375, title: 'Kids > Toys > Toy cars, trains & vehicles', keywords: ['toy car','toy train','hot wheels','matchbox'] },
  { id: 1731, title: 'Kids > Toys > Dolls & accessories', keywords: ['doll','barbie','dolls house'] },
  { id: 3314, title: 'Kids > Toys > Arts & crafts', keywords: ['arts crafts','colouring','painting','craft kit'] },
  { id: 3344, title: 'Kids > Toys > Baby activities & toys', keywords: ['baby toy','rattle','teether','activity mat'] },
  { id: 1725, title: 'Kids > Toys > Electronic toys', keywords: ['electronic toy','vtech','leapfrog'] },
  { id: 3336, title: 'Kids > Toys > Novelty & fidget toys', keywords: ['fidget','fidget spinner','slime','novelty toy'] },
  { id: 1763, title: 'Kids > Toys > Educational toys', keywords: ['educational toy','learning toy','montessori'] },
  { id: 3329, title: 'Kids > Toys > Dress up & pretend play', keywords: ['pretend play','play kitchen','dress up'] },
  { id: 1771, title: 'Kids > Toys > Outdoor & sports toys', keywords: ['outdoor toy','ride on','scooter','trampoline'] },
  { id: 1766, title: 'Kids > Toys > Musical toys', keywords: ['musical toy','toy instrument','xylophone'] },
  // Kids > Pushchairs, carriers & car seats
  { id: 1612, title: 'Kids > Buggies & pushchairs', keywords: ['stroller','pushchair','pram','buggy'] },
  { id: 3383, title: 'Kids > Car seats', keywords: ['car seat','child seat'] },
  { id: 3384, title: 'Kids > Booster seats', keywords: ['booster seat'] },
  { id: 3461, title: 'Kids > Baby carriers & wraps', keywords: ['baby carrier','sling','wrap','baby wrap'] },
  { id: 1511, title: 'Kids > Buggy accessories', keywords: ['buggy accessories','pram accessories'] },
  { id: 3385, title: 'Kids > Car seat accessories', keywords: ['car seat accessories'] },
  // Kids > Sleep & bedding
  { id: 3297, title: 'Kids > Bedding, blankets & throws', keywords: ['baby blanket','kids bedding','cot bedding'] },
  { id: 3307, title: 'Kids > Sleep sacks & wearable blankets', keywords: ['sleep sack','sleeping bag','wearable blanket'] },
  { id: 3309, title: 'Kids > Swaddles', keywords: ['swaddle'] },
  { id: 3303, title: 'Kids > Baby monitors', keywords: ['baby monitor'] },
  { id: 3306, title: 'Kids > Nightlights', keywords: ['nightlight','night light'] },
  // Kids > Nursing & feeding
  { id: 3444, title: 'Kids > Cups, dishes & utensils', keywords: ['sippy cup','baby plate','baby bowl','baby spoon'] },
  { id: 3435, title: 'Kids > Bottle feeding', keywords: ['baby bottle','bottles'] },
  { id: 3453, title: 'Kids > Breastfeeding', keywords: ['breast pump','nursing bra','breastfeeding'] },
  { id: 3434, title: 'Kids > Bibs', keywords: ['bib','weaning bib'] },
  { id: 3458, title: 'Kids > Dummies & soothers', keywords: ['dummy','soother','pacifier'] },
  { id: 3460, title: 'Kids > Sterilisers', keywords: ['steriliser','bottle steriliser'] },
  { id: 3450, title: 'Kids > High chairs', keywords: ['high chair','highchair'] },
  { id: 3443, title: 'Kids > Muslins & burp cloths', keywords: ['muslin','burp cloth'] },
  // Kids > Bathing & changing
  { id: 3394, title: 'Kids > Baby changing bags', keywords: ['changing bag','nappy bag'] },
  { id: 3412, title: 'Kids > Bathing', keywords: ['baby bath','bath seat','bath toy'] },
  { id: 3417, title: 'Kids > Potties', keywords: ['potty','toilet training','potty training'] },
  // Kids > Other
  { id: 1498, title: 'Kids > Furniture & decor', keywords: ['kids furniture','cot','crib','baby furniture','nursery'] },
  { id: 1501, title: 'Kids > School supplies', keywords: ['school','lunch box','pencil case','school bag'] },
  { id: 1502, title: 'Kids > Other kids items', keywords: ['kids','children'] },
  // HOME
  { id: 1934, title: 'Home > Home accessories', keywords: ['decoration','ornament','vase','candle','frame','mirror','wall art','home decor'] },
  { id: 1920, title: 'Home > Tableware', keywords: ['plate','mug','cup','bowl','glass','cutlery','dinnerware'] },
  { id: 1919, title: 'Home > Textiles', keywords: ['blanket','pillow','cushion','towel','bedding','curtain','rug','duvet','throw'] },
  { id: 2915, title: 'Home > Celebrations & holidays', keywords: ['christmas','easter','halloween','party','decorations'] },
  { id: 5106, title: 'Home > Pet care', keywords: ['pet','dog','cat','collar','lead','pet bed','pet toy'] },
  { id: 3811, title: 'Home > Tools & DIY', keywords: ['tools','drill','screwdriver','diy','hardware'] },
  { id: 5428, title: 'Home > Office supplies', keywords: ['office','stationery','desk organiser','pen','notebook'] },
  { id: 3477, title: 'Home > Kitchen tools', keywords: ['utensil','grater','peeler','kitchen tool'] },
  { id: 3474, title: 'Home > Small kitchen appliances', keywords: ['kettle','toaster','blender','air fryer','coffee machine'] },
  { id: 3812, title: 'Home > Outdoor & garden', keywords: ['garden','outdoor','plant pot','planter','bbq','garden furniture'] },
  { id: 3476, title: 'Home > Cookware & bakeware', keywords: ['pan','pot','baking tray','casserole','cookware'] },
  { id: 3478, title: 'Home > Household care', keywords: ['cleaning','storage','organiser','laundry'] },
  { id: 3154, title: 'Home > Furniture', keywords: ['furniture','shelf','table','chair','desk','cabinet'] },
  { id: 3475, title: 'Home > Large appliances', keywords: ['washing machine','fridge','oven','dishwasher'] },
  // ENTERTAINMENT
  { id: 2319, title: 'Entertainment > Books > Literature & fiction', keywords: ['novel','fiction','book','paperback','hardback'] },
  { id: 2318, title: 'Entertainment > Books > Kids & young adults', keywords: ['children book','kids book','young adult'] },
  { id: 2320, title: 'Entertainment > Books > Non-fiction', keywords: ['non-fiction','nonfiction','biography','history','cookbook'] },
  { id: 5426, title: 'Entertainment > Books > Textbooks', keywords: ['textbook','study','revision','university'] },
  { id: 5425, title: 'Entertainment > Books > Comics, manga & graphic novels', keywords: ['comic','manga','graphic novel'] },
  { id: 5427, title: 'Entertainment > Books > Colouring & activity books', keywords: ['colouring book','activity book','puzzle book'] },
  { id: 3045, title: 'Entertainment > Video > DVD', keywords: ['dvd','dvds'] },
  { id: 3044, title: 'Entertainment > Video > Blu-ray', keywords: ['blu-ray','bluray','blu ray'] },
  { id: 3048, title: 'Entertainment > Video > VHS', keywords: ['vhs','video tape'] },
  { id: 3042, title: 'Entertainment > Video > 4K Blu-ray', keywords: ['4k blu-ray','4k'] },
  { id: 3039, title: 'Entertainment > Music > CDs', keywords: ['cd','cds','album'] },
  { id: 3041, title: 'Entertainment > Music > Vinyl records', keywords: ['vinyl','record','lp','12 inch'] },
  { id: 3038, title: 'Entertainment > Music > Audio cassettes', keywords: ['cassette','tape','audio cassette'] },
  { id: 5424, title: 'Entertainment > Magazines', keywords: ['magazine','magazines'] },
  // ELECTRONICS
  { id: 3026, title: 'Electronics > Video games > Games', keywords: ['video game','game','ps5 game','ps4 game','xbox game','switch game'] },
  { id: 3025, title: 'Electronics > Video games > Consoles', keywords: ['console','playstation','xbox','nintendo','ps5','ps4','switch'] },
  { id: 3570, title: 'Electronics > Video games > Controllers', keywords: ['controller','gamepad','joystick'] },
  { id: 3571, title: 'Electronics > Video games > Gaming headsets', keywords: ['gaming headset'] },
  { id: 3576, title: 'Electronics > Video games > Virtual reality', keywords: ['vr','virtual reality','oculus','quest'] },
  { id: 3024, title: 'Electronics > Video games > Accessories', keywords: ['gaming accessories','gaming mouse','gaming keyboard'] },
  { id: 3661, title: 'Electronics > Mobile phones', keywords: ['phone','iphone','samsung','mobile','smartphone'] },
  { id: 3662, title: 'Electronics > Phone accessories', keywords: ['phone case','screen protector','phone charger','phone accessories'] },
  { id: 3580, title: 'Electronics > Computers > Laptops', keywords: ['laptop','macbook','chromebook'] },
  { id: 3581, title: 'Electronics > Computers > Desktop computers', keywords: ['desktop','pc','computer'] },
  { id: 3590, title: 'Electronics > Computers > Monitors', keywords: ['monitor','screen','display'] },
  { id: 3587, title: 'Electronics > Computers > Keyboards', keywords: ['keyboard','mechanical keyboard'] },
  { id: 3588, title: 'Electronics > Computers > Mice', keywords: ['mouse','mice','trackpad'] },
  { id: 3585, title: 'Electronics > Computers > Laptop accessories', keywords: ['laptop case','laptop bag','laptop stand'] },
  { id: 3582, title: 'Electronics > Computers > Parts & components', keywords: ['graphics card','gpu','ram','ssd','cpu','motherboard'] },
  { id: 3586, title: 'Electronics > Computers > Docking stations & USB hubs', keywords: ['dock','usb hub','docking station'] },
  { id: 3593, title: 'Electronics > Computers > Webcams', keywords: ['webcam'] },
  { id: 3595, title: 'Electronics > Computers > Printers', keywords: ['printer','scanner'] },
  { id: 3584, title: 'Electronics > Computers > Computer accessories', keywords: ['computer accessories'] },
  { id: 3678, title: 'Electronics > Audio > Headphones & earbuds', keywords: ['headphones','earphones','airpods','earbuds'] },
  { id: 3681, title: 'Electronics > Audio > Portable speakers', keywords: ['speaker','bluetooth speaker','portable speaker'] },
  { id: 3682, title: 'Electronics > Audio > Smart speakers', keywords: ['smart speaker','echo','alexa','google home'] },
  { id: 3683, title: 'Electronics > Audio > Home audio systems', keywords: ['home audio','hi-fi','stereo','sound system','soundbar'] },
  { id: 3679, title: 'Electronics > Audio > Handheld music players', keywords: ['mp3 player','ipod','walkman'] },
  { id: 3680, title: 'Electronics > Audio > Portable radios', keywords: ['radio','portable radio','dab radio'] },
  { id: 3686, title: 'Electronics > Audio > Audio accessories', keywords: ['audio cable','aux cable','audio accessories'] },
  { id: 3060, title: 'Electronics > Cameras > Cameras', keywords: ['camera','dslr','mirrorless','compact camera'] },
  { id: 3061, title: 'Electronics > Cameras > Lenses', keywords: ['lens','camera lens'] },
  { id: 3716, title: 'Electronics > Cameras > Camera drones', keywords: ['drone','camera drone','dji'] },
  { id: 3067, title: 'Electronics > Cameras > Tripods & monopods', keywords: ['tripod','monopod'] },
  { id: 3062, title: 'Electronics > Cameras > Flashes', keywords: ['flash','speedlight'] },
  { id: 3063, title: 'Electronics > Cameras > Memory cards', keywords: ['memory card','sd card','micro sd'] },
  { id: 3059, title: 'Electronics > Cameras > Accessories', keywords: ['camera accessories','camera bag','camera strap'] },
  { id: 3567, title: 'Electronics > Tablets & e-readers', keywords: ['tablet','ipad','kindle','e-reader'] },
  { id: 3569, title: 'Electronics > Beauty & personal care electronics', keywords: ['hair straightener','hair dryer','electric toothbrush'] },
  { id: 3568, title: 'Electronics > TV & home cinema', keywords: ['tv','television','projector','home cinema'] },
  { id: 3004, title: 'Electronics > Wearables', keywords: ['smartwatch','apple watch','fitbit','fitness tracker'] },
  { id: 2995, title: 'Electronics > Other devices', keywords: ['charger','cable','adapter','electronics','gadget','tech'] },
  // HOBBIES & COLLECTABLES
  { id: 4874, title: 'Hobbies > Trading cards', keywords: ['trading cards','pokemon cards','yugioh','football cards'] },
  { id: 5151, title: 'Hobbies > Arts & crafts', keywords: ['arts','crafts','sewing','knitting','crochet','yarn','fabric'] },
  { id: 4901, title: 'Hobbies > Memorabilia', keywords: ['memorabilia','signed','autograph','collectible'] },
  { id: 4881, title: 'Hobbies > Board games', keywords: ['board game','monopoly','chess','scrabble'] },
  { id: 4882, title: 'Hobbies > Puzzles', keywords: ['puzzle','jigsaw'] },
  { id: 4895, title: 'Hobbies > Coins & banknotes', keywords: ['coin','banknote','numismatic'] },
  { id: 4883, title: 'Hobbies > Tabletop & miniature gaming', keywords: ['warhammer','miniature','tabletop','d&d','dungeons'] },
  { id: 4825, title: 'Hobbies > Musical instruments & gear', keywords: ['guitar','keyboard','drum','instrument','amplifier','music'] },
  { id: 4916, title: 'Hobbies > Gaming accessories', keywords: ['gaming accessories'] },
  { id: 4894, title: 'Hobbies > Postcards', keywords: ['postcard','postcards'] },
  { id: 4888, title: 'Hobbies > Stamps', keywords: ['stamp','stamps','philately'] },
  { id: 4906, title: 'Hobbies > Collectables storage', keywords: ['display case','storage box','binder'] },
  // SPORTS
  { id: 4340, title: 'Sports > Equestrian', keywords: ['horse','equestrian','saddle','riding','bridle'] },
  { id: 4334, title: 'Sports > Fitness, running & yoga', keywords: ['fitness','running','yoga','weights','gym equipment','treadmill'] },
  { id: 4333, title: 'Sports > Cycling', keywords: ['cycling','bicycle','bike','helmet','cycling jersey'] },
  { id: 4336, title: 'Sports > Water sports', keywords: ['swimming','diving','surfing','wetsuit','snorkelling','kayak'] },
  { id: 4335, title: 'Sports > Outdoor sports', keywords: ['hiking','camping','climbing','tent','sleeping bag','backpack'] },
  { id: 4337, title: 'Sports > Team sports', keywords: ['football','rugby','cricket','basketball','hockey','netball'] },
  { id: 4339, title: 'Sports > Golf', keywords: ['golf','golf club','golf ball','golf bag'] },
  { id: 4342, title: 'Sports > Boxing & martial arts', keywords: ['boxing','martial arts','gloves','mma','karate'] },
  { id: 4341, title: 'Sports > Skateboards & scooters', keywords: ['skateboard','scooter','rollerblades','roller skates'] },
  { id: 4343, title: 'Sports > Casual sports & games', keywords: ['darts','table tennis','badminton set','croquet'] },
  { id: 4344, title: 'Sports > Winter sports', keywords: ['skiing','snowboard','ski','ice skating'] },
  { id: 4338, title: 'Sports > Racquet sports', keywords: ['tennis','badminton','squash','racket','racquet'] },
];

const COLORS = [
  { id: 1, label: 'Black' }, { id: 12, label: 'White' }, { id: 3, label: 'Grey' },
  { id: 9, label: 'Blue' }, { id: 7, label: 'Red' }, { id: 10, label: 'Green' },
  { id: 8, label: 'Yellow' }, { id: 5, label: 'Pink' }, { id: 11, label: 'Orange' },
  { id: 6, label: 'Purple' }, { id: 2, label: 'Brown' }, { id: 4, label: 'Beige' },
  { id: 18, label: 'Cream' }, { id: 15, label: 'Multicolour' },
  { id: 16, label: 'Khaki' }, { id: 17, label: 'Turquoise' },
  { id: 13, label: 'Silver' }, { id: 14, label: 'Gold' },
  { id: 25, label: 'Navy' }, { id: 21, label: 'Burgundy' },
  { id: 20, label: 'Coral' }, { id: 24, label: 'Light blue' },
];

const COLOR_ALIASES = {
  'dark blue': 'Navy', 'indigo': 'Navy', 'midnight': 'Navy', 'navy blue': 'Navy',
  'royal blue': 'Blue', 'cobalt': 'Blue', 'electric blue': 'Blue',
  'baby blue': 'Light blue', 'sky blue': 'Light blue', 'pale blue': 'Light blue', 'powder blue': 'Light blue',
  'off white': 'Cream', 'off-white': 'Cream', 'ivory': 'Cream', 'ecru': 'Cream', 'nude': 'Cream', 'bone': 'Cream',
  'hot pink': 'Pink', 'magenta': 'Pink', 'fuchsia': 'Pink', 'rose': 'Pink', 'salmon': 'Pink', 'blush': 'Pink',
  'dark red': 'Burgundy', 'wine': 'Burgundy', 'maroon': 'Burgundy', 'oxblood': 'Burgundy', 'bordeaux': 'Burgundy', 'crimson': 'Burgundy',
  'olive': 'Khaki', 'army green': 'Khaki', 'military green': 'Khaki', 'sage': 'Khaki',
  'forest green': 'Green', 'dark green': 'Green', 'emerald': 'Green', 'mint': 'Green', 'lime': 'Green', 'moss': 'Green',
  'lilac': 'Purple', 'lavender': 'Purple', 'violet': 'Purple', 'plum': 'Purple', 'mauve': 'Purple',
  'camel': 'Brown', 'tan': 'Brown', 'chocolate': 'Brown', 'tobacco': 'Brown', 'rust': 'Brown', 'caramel': 'Brown', 'mocha': 'Brown',
  'teal': 'Turquoise', 'aqua': 'Turquoise', 'cyan': 'Turquoise',
  'charcoal': 'Grey', 'light grey': 'Grey', 'dark grey': 'Grey', 'gray': 'Grey', 'silver grey': 'Grey', 'slate': 'Grey',
  'rose gold': 'Gold', 'champagne': 'Gold', 'bronze': 'Gold',
  'multicolor': 'Multicolour', 'multi': 'Multicolour', 'multi-color': 'Multicolour', 'multicoloured': 'Multicolour', 'patterned': 'Multicolour', 'floral': 'Multicolour', 'striped': 'Multicolour', 'printed': 'Multicolour',
  'coral pink': 'Coral', 'peach': 'Coral',
  'mustard': 'Yellow', 'lemon': 'Yellow',
  'tangerine': 'Orange', 'amber': 'Orange',
  'jet black': 'Black', 'noir': 'Black',
  'pure white': 'White', 'snow': 'White',
  'beige': 'Beige',
};

const CLOTHING_CATEGORY_IDS = new Set(
  CATEGORIES
    .filter(c => {
      const title = (c.title || '').toLowerCase();
      const isWMK = /^(women|men|kids) > /i.test(c.title || '');
      const isNonClothing = /(shoes|bags|jewellery|accessories|beauty|grooming|toys|pushchairs|nursing|bathing|sleep)/i.test(title);
      return isWMK && !isNonClothing;
    })
    .map(c => c.id)
);

const HIGH_RISK_BRANDS = new Set([
  'gucci','louis vuitton','lv','prada','balenciaga','dior','christian dior',
  'chanel','burberry','moncler','stone island','canada goose','nike','jordan',
  'air jordan','off-white','off white','hermes','hermès','yves saint laurent',
  'ysl','saint laurent','fendi','versace','armani','giorgio armani','emporio armani',
  'ralph lauren','polo ralph lauren','patagonia','supreme','palace','trapstar',
  'corteiz','the north face','north face','arc\'teryx','arcteryx','bottega veneta',
  'celine','céline','goyard','loewe','valentino','givenchy','loro piana',
  'rolex','omega','cartier','audemars piguet','patek philippe','tag heuer',
]);

const ANALYSIS_MODEL = process.env.ANALYSIS_MODEL || 'claude-sonnet-4-6';

const CATALOG_TTL_MS = 24 * 60 * 60 * 1000;

module.exports = {
  WIZARD_STEPS,
  ADMIN_VINTED_USERNAMES,
  CONDITIONS,
  PACKAGE_SIZES,
  CATEGORIES,
  COLORS,
  COLOR_ALIASES,
  CLOTHING_CATEGORY_IDS,
  HIGH_RISK_BRANDS,
  ANALYSIS_MODEL,
  CATALOG_TTL_MS,
};
